name: chat
description: Chat Plugin
version: 1.1.1
homepage:

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  file_picker: ^9.1.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  uuid: ^4.5.1
  intl: ^0.19.0
  photo_view: ^0.15.0
  diffutil_dart: ^4.0.1
  visibility_detector: ^0.4.0+2
  adaptive_dialog: ^2.4.0
  socket_io_client: ^3.0.2
  cached_network_image: ^3.4.1
  jwt_decode: ^0.3.1
  auto_size_text: ^3.0.0
  overlay_support: ^2.0.1
  email_validator: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^4.0.0
  emoji_picker_flutter: ^4.3.0
  scrollable_positioned_list: ^0.3.8
  swipeable_tile: ^2.0.1
  flutter_file_dialog: ^3.0.2
  dio: ^5.8.0+1
  audioplayers: ^6.4.0
  rich_text_controller: ^3.0.1
  badges: ^3.1.2
  url_launcher: ^6.3.1
  saver_gallery: ^4.0.1
  shared_preferences: ^2.5.2
  flex_color_picker: ^3.7.0
  rxdart: ^0.28.0
  keyboard_actions: ^4.2.0
  open_filex: ^4.7.0
  permission_handler: ^11.4.0
  image_picker_android: ^0.8.12+22

  path: ^1.9.1

#dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: wao.chat.plugin.leovu.chat
        pluginClass: ChatPlugin
      ios:
        pluginClass: ChatPlugin
      web:
        pluginClass: ChatWeb
        fileName: chat_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/meme/panda/
    - assets/
    - assets/meme/usagyuun/
    - assets/meme/mimicat/
    - assets/messages.json
    - assets/chat_en.json
    - assets/chat_vi.json
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
