#spring:
#  application:
#    name: msa
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/msa_1
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  jackson:
#    deserialization:
#      adjust-dates-to-context-time-zone: false
#  data:
#    redis:
#      host: redis
#      port: 6379
#      password:
#      database: 0
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600000
#      cache-null-values: true
#
#  quartz:
#    job-store-type: jdbc
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: MyScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            misfireThreshold: 60000
#    jdbc:
#      initialize-schema: always
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: anhquan20102003@gmail.com
#    password: gofrptljwgjptmmg
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#server:
#  port: 1081
#  servlet:
#    context-path: /msa/api
#
#jwt:
#  signerKey: FH7jrUqilRiuOZJnYs!B49FiV3BRG2EKW/xrC!BvuIHeQdy6fmnw3bZD3c2GycRDqbUYgL-Z4L6rkKMU8FrQzaLvzKQFOSZmhss2?37HqiCozilTgcQd-/iqfpQGwMLZ!OjQ-O8jVfhf73CxoPDR2bhg2LWIHluwxt293ezeX/Zc0ijLJyTCBIO!-QjdBlryikLZYxzzHj/gwz8-vguokfXzpQPJbw8e8VYfLTThTlqj8plRVm1BeuPzRJgDWsy?
#  valid-duration: 36000000000000000
#  refreshable-duration: 36000000000000000
#
#goship:
#  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNmMzdjOTljZGY3NjdmMGI2NWUyMTQ4NmRmOWRlYWQyZjk4ZjY3YmJhNGJmMDNhYjA5ZGQwMGM4YjMwNDkxOGM0MDkxZDgyNjMzNzg2N2RiIn0.eyJhdWQiOiIxNjYiLCJqdGkiOiJjZjM3Yzk5Y2RmNzY3ZjBiNjVlMjE0ODZkZjlkZWFkMmY5OGY2N2JiYTRiZjAzYWIwOWRkMDBjOGIzMDQ5MThjNDA5MWQ4MjYzMzc4NjdkYiIsImlhdCI6MTc0NTE0Njk1NSwibmJmIjoxNzQ1MTQ2OTU1LCJleHAiOjE3NzY2ODI5NTUsInN1YiI6IjM1MzkiLCJzY29wZXMiOltdfQ.BcSveRBtwtBi9QVQCdV5EE9e9fZ6B4tHmNsPf-OTMZ017WanwfKSTfEbawN-3m2wgUehyklRQpge3esjGTJha1hKaGK6DtviMFVVutyvkHTBG0l7UtSlNDDlkvgkSmpczShMnC0Mth5W33FzCrzHWRLyJgZkbPItabyZEmXtSR2VfzKBDyloMzDefX6U_BJgbLiSCyaLzA7UoDNVOCg5mRGR8axic23njWsIoCFzx-vHX_2hcKxx2meiAtHgSbYlB8oss_9O27qTEroBS5Rg61mqR_oSoXrBHBLBSvv5b2aiDsESqSpdB8za78Kbi95SQubTJ0uTLGTtoEXEPytWks3_mZtsK-1oLrpwBpx9M-bYlFU9IKu9JACLiA0KzQrcGI0SUVDvyrx4-hBYrT1E8XrSKuwoMYBscTDT-G7DW4Y6Rg_rJkE56PxVPiErqUOTnlzAoIgGXSjdV_NZS2GFGP5vX7wjjnzaEcXq-4gcJ5ZTJNqk-922RzwVO4zXdbJR9OfrOtCIdErjdbacs-6E5taTLyXYxyEczUxDyVxG8nuzIwuH0iKuVTnG1dt3tkt0IVheMcJSQVYUx74giW01V8mlgvVQbJwzQHFt2Kueid3VQSvOeOr6FpQLoycnrlrMeZTyDIX1WnepHoyawDrT7rgkJxKe2RiwQpX3UYPnJlo
#  url: http://sandbox.goship.io/api/v2
#
#zero-bounce:
#  api:
#    key: 5497d5ce12ee486da7951f94d381b2c4
#
#vnpay:
#  tmnCode: M4XRKBHC
#  hashSecret: MTXRPACIMWA09YVFD1GMVW1WJPUPN491
#  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#  returnUrl: http://localhost:1081/msa/api/payment/vnpay/callback
#  apiUrl: http://sandbox.vnpayment.vn/merchant_webapi/merchant.html
spring:
  application:
    name: msa
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/msa_project?useSSL=false&serverTimezone=UTC
    username: root
    password: vPjGPNZHubvCNTdPfWwSoeWAWyqAvaLo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  data:
    redis:
      host: redis
      port: 6379
      password:
      database: 0
  cache:
    type: none
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 60000
            dataSource: myDS
          dataSource:
            myDS:
              driver: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://mysql.railway.internal:3306/msa_project
              user: root
              password: vPjGPNZHubvCNTdPfWwSoeWAWyqAvaLo


  mail:
    host: smtp.gmail.com
    port: 587
    username: anhquan20102003@gmail.com
    password: gofrptljwgjptmmg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:1081}
  servlet:
    context-path: /msa/api

jwt:
  signerKey: FH7jrUqilRiuOZJnYs!B49FiV3BRG2EKW/xrC!BvuIHeQdy6fmnw3bZD3c2GycRDqbUYgL-Z4L6rkKMU8FrQzaLvzKQFOSZmhss2?37HqiCozilTgcQd-/iqfpQGwMLZ!OjQ-O8jVfhf73CxoPDR2bhg2LWIHluwxt293ezeX/Zc0ijLJyTCBIO!-QjdBlryikLZYxzzHj/gwz8-vguokfXzpQPJbw8e8VYfLTThTlqj8plRVm1BeuPzRJgDWsy?
  valid-duration: 36000000000000000
  refreshable-duration: 36000000000000000

goship:
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImNmMzdjOTljZGY3NjdmMGI2NWUyMTQ4NmRmOWRlYWQyZjk4ZjY3YmJhNGJmMDNhYjA5ZGQwMGM4YjMwNDkxOGM0MDkxZDgyNjMzNzg2N2RiIn0.eyJhdWQiOiIxNjYiLCJqdGkiOiJjZjM3Yzk5Y2RmNzY3ZjBiNjVlMjE0ODZkZjlkZWFkMmY5OGY2N2JiYTRiZjAzYWIwOWRkMDBjOGIzMDQ5MThjNDA5MWQ4MjYzMzc4NjdkYiIsImlhdCI6MTc0NTE0Njk1NSwibmJmIjoxNzQ1MTQ2OTU1LCJleHAiOjE3NzY2ODI5NTUsInN1YiI6IjM1MzkiLCJzY29wZXMiOltdfQ.BcSveRBtwtBi9QVQCdV5EE9e9fZ6B4tHmNsPf-OTMZ017WanwfKSTfEbawN-3m2wgUehyklRQpge3esjGTJha1hKaGK6DtviMFVVutyvkHTBG0l7UtSlNDDlkvgkSmpczShMnC0Mth5W33FzCrzHWRLyJgZkbPItabyZEmXtSR2VfzKBDyloMzDefX6U_BJgbLiSCyaLzA7UoDNVOCg5mRGR8axic23njWsIoCFzx-vHX_2hcKxx2meiAtHgSbYlB8oss_9O27qTEroBS5Rg61mqR_oSoXrBHBLBSvv5b2aiDsESqSpdB8za78Kbi95SQubTJ0uTLGTtoEXEPytWks3_mZtsK-1oLrpwBpx9M-bYlFU9IKu9JACLiA0KzQrcGI0SUVDvyrx4-hBYrT1E8XrSKuwoMYBscTDT-G7DW4Y6Rg_rJkE56PxVPiErqUOTnlzAoIgGXSjdV_NZS2GFGP5vX7wjjnzaEcXq-4gcJ5ZTJNqk-922RzwVO4zXdbJR9OfrOtCIdErjdbacs-6E5taTLyXYxyEczUxDyVxG8nuzIwuH0iKuVTnG1dt3tkt0IVheMcJSQVYUx74giW01V8mlgvVQbJwzQHFt2Kueid3VQSvOeOr6FpQLoycnrlrMeZTyDIX1WnepHoyawDrT7rgkJxKe2RiwQpX3UYPnJlo
  url: http://sandbox.goship.io/api/v2

zero-bounce:
  api:
    key: 5497d5ce12ee486da7951f94d381b2c4

vnpay:
  tmnCode: M4XRKBHC
  hashSecret: MTXRPACIMWA09YVFD1GMVW1WJPUPN491
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:1081/msa/api/payment/vnpay/callback
  apiUrl: http://sandbox.vnpayment.vn/merchant_webapi/merchant.html
